API_KEY_BINANCE:
API_SECRET_KEY_BINANCE:
API_KEY_KRAKEN:
API_SECRET_KEY_KRAKEN:

API_KEY_COINBASE:
API_SECRET_KEY_COINBASE:
API_PASSPHRASE_COINBASE:
MONGODB_URI: 

EXCHANGE: 
  - binance
  - kraken
  - coinbase
API_HOST: localhost
API_PORT: 8081 